# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectureProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=40, null=True)),
                ('description_en', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ua', models.TextField(blank=True, max_length=150, null=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=40, null=True)),
                ('description_en', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ua', models.TextField(blank=True, max_length=150, null=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=40, null=True)),
                ('description_en', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ua', models.TextField(blank=True, max_length=150, null=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DesignType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=40, null=True)),
                ('description_en', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ua', models.TextField(blank=True, max_length=150, null=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ua', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='designproject',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archapp.DesignType'),
        ),
        migrations.AddField(
            model_name='designimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archapp.DesignProject'),
        ),
        migrations.AddField(
            model_name='architectureproject',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archapp.ArchitectureType'),
        ),
        migrations.AddField(
            model_name='architectureimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archapp.ArchitectureProject'),
        ),
    ]
