# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archapp', '0002_auto_20180330_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectureproject',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='designproject',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
