# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archapp', '0003_auto_20180410_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectureproject',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='architectureproject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 11, 17, 25, 0, 98000)),
        ),
        migrations.AddField(
            model_name='architectureproject',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='architectureproject',
            name='location_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='architectureproject',
            name='location_ua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='architectureproject',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='designproject',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='designproject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 11, 17, 25, 0, 99000)),
        ),
        migrations.AddField(
            model_name='designproject',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='designproject',
            name='location_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='designproject',
            name='location_ua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='designproject',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
