# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archapp', '0004_auto_20180411_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('img', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='architectureproject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 17, 33, 53, 614000)),
        ),
        migrations.AlterField(
            model_name='architectureproject',
            name='year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='designproject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 17, 33, 53, 615000)),
        ),
        migrations.AlterField(
            model_name='designproject',
            name='year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
