# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archapp', '0005_auto_20180417_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('img', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='architectureproject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 16, 20, 34, 313000)),
        ),
        migrations.AlterField(
            model_name='designproject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 16, 20, 34, 314000)),
        ),
        migrations.AddField(
            model_name='homeproject',
            name='archproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archapp.ArchitectureProject'),
        ),
    ]
