# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archapp', '0006_auto_20180419_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=40, null=True)),
                ('description_en', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ua', models.TextField(blank=True, max_length=150, null=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ua', models.CharField(max_length=100)),
                ('location_en', models.CharField(blank=True, max_length=200, null=True)),
                ('location_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('location_ua', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=9, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to=b'')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 6, 6, 16, 35, 55, 677000))),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=40, null=True)),
                ('description_en', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ua', models.TextField(blank=True, max_length=150, null=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FloatingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='FloatingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=40, null=True)),
                ('description_en', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ua', models.TextField(blank=True, max_length=150, null=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ua', models.CharField(max_length=100)),
                ('location_en', models.CharField(blank=True, max_length=200, null=True)),
                ('location_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('location_ua', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=9, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to=b'')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 6, 6, 16, 35, 55, 679000))),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloatingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=40, null=True)),
                ('description_en', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ua', models.TextField(blank=True, max_length=150, null=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteriorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=40, null=True)),
                ('description_en', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ua', models.TextField(blank=True, max_length=150, null=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ua', models.CharField(max_length=100)),
                ('location_en', models.CharField(blank=True, max_length=200, null=True)),
                ('location_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('location_ua', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=9, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to=b'')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 6, 6, 16, 35, 55, 678000))),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteriorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=40, null=True)),
                ('title_ua', models.CharField(blank=True, max_length=40, null=True)),
                ('description_en', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=150, null=True)),
                ('description_ua', models.TextField(blank=True, max_length=150, null=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ua', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='architectureimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='architectureproject',
            name='type',
        ),
        migrations.RemoveField(
            model_name='designimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='designproject',
            name='type',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='archproject',
        ),
        migrations.DeleteModel(
            name='ArchitectureImage',
        ),
        migrations.DeleteModel(
            name='ArchitectureProject',
        ),
        migrations.DeleteModel(
            name='ArchitectureType',
        ),
        migrations.DeleteModel(
            name='DesignImage',
        ),
        migrations.DeleteModel(
            name='DesignProject',
        ),
        migrations.DeleteModel(
            name='DesignType',
        ),
        migrations.AddField(
            model_name='interiorproject',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archapp.InteriorType'),
        ),
        migrations.AddField(
            model_name='interiorimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archapp.InteriorProject'),
        ),
        migrations.AddField(
            model_name='floatingproject',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archapp.FloatingType'),
        ),
        migrations.AddField(
            model_name='floatingimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archapp.FloatingProject'),
        ),
        migrations.AddField(
            model_name='buildingproject',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archapp.BuildingType'),
        ),
        migrations.AddField(
            model_name='buildingimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archapp.BuildingProject'),
        ),
        migrations.AddField(
            model_name='homeproject',
            name='buildingProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archapp.BuildingProject'),
        ),
        migrations.AddField(
            model_name='homeproject',
            name='interiorProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archapp.InteriorProject'),
        ),
    ]
