# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archapp', '0007_auto_20180606_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingproject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 16, 39, 33, 473000)),
        ),
        migrations.AlterField(
            model_name='floatingproject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 16, 39, 33, 475000)),
        ),
        migrations.AlterField(
            model_name='interiorproject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 16, 39, 33, 474000)),
        ),
    ]
