# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archapp', '0008_auto_20180606_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeproject',
            name='buildingProject',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='interiorProject',
        ),
        migrations.AddField(
            model_name='buildingproject',
            name='text_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='buildingproject',
            name='text_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='buildingproject',
            name='text_ua',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='floatingproject',
            name='text_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='floatingproject',
            name='text_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='floatingproject',
            name='text_ua',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='interiorproject',
            name='text_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='interiorproject',
            name='text_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='interiorproject',
            name='text_ua',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='buildingproject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 14, 24, 13, 770000)),
        ),
        migrations.AlterField(
            model_name='floatingproject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 14, 24, 13, 772000)),
        ),
        migrations.AlterField(
            model_name='interiorproject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 14, 24, 13, 772000)),
        ),
        migrations.AlterField(
            model_name='interiorproject',
            name='img',
            field=models.FileField(upload_to=b''),
        ),
        migrations.DeleteModel(
            name='HomeProject',
        ),
    ]
